name: 00-installer-Plugin

on:
  workflow_dispatch:

jobs:

################# Pipeline permissions ################
  build:
    permissions:
      checks: write
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:

    - name: Determine Target Directory
      id: determine_directory
      run: |
        if [ "${{ github.event_name }}" = 'push' ] && [[ "${{ github.event_ref }}" =~ ^refs/tags/ ]]; then
          echo "directory=launch-release-local/automation-hosts/agentctl/" >> $JFROG_UPLOAD_DIR
        else
          echo "directory=launch-release-local/automation-hosts/agentctl-testing/" >> $JFROG_UPLOAD_DIR
        fi

    - name: Echo
      run: |
        echo "$JFROG_UPLOAD_DIR"
