name: 00-installer-Plugin

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:

################# Pipeline permissions ################
  build:
    permissions:
      checks: write
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:

    - name: Determine Target Directory
      id: determine_directory
      run: |
        if [ "${{ github.event_name }}" = 'push' ] && [ -n "${{ github.ref }}" ]; then
          echo "directory=launch-release-local/automation-hosts/agentctl/" >> $GITHUB_ENV
        else
          echo "directory=launch-release-local/automation-hosts/agentctl-testing/" >> $GITHUB_ENV
        fi

    - name: Echo
      run: |
        echo "Using directory: $directory"
